# Change this if you have this stuff somewhere else.

TCLINC = /usr/local/lib/tcl8.0
TKINC  = /usr/local/lib/tk8.0
X11INC = /usr/X11/include

CFLAGS = -Wall -fPIC -O3 -I$(TCLINC) -I$(TKINC) -I$(X11INC)

CC = gcc

all: ext.so

ext.so: ext.o
        ld -b ext.o -o ext.so

